name: MMOMail
version: '${version}'
main: com.binggre.mmomail.MMOMail
api-version: '1.20'
authors: [ binggre ]
depend: [ 'BinggreAPI', 'MongoLibraryPlugin', 'VelocitySocketClient', 'MMOPlayerData' ]
commands:
  메일: